kind: pipeline
type: kubernetes
name: default

steps:
- name: install
  image: amazon/aws-sam-cli-build-image-go1.x
  volumes:
    - name: deps
      path: /go
  commands:
  - go mod download

- name: test
  image: amazon/aws-sam-cli-build-image-go1.x
  volumes:
    - name: deps
      path: /go
  commands:
  - make test

- name: build
  image: amazon/aws-sam-cli-build-image-go1.x
  volumes:
    - name: deps
      path: /go
  commands:
  - make build

volumes:
- name: deps
  temp: {}
