kind: pipeline
type: kubernetes
name: default

steps:
- name: install
  image: golang:1.21
  volumes:
    - name: deps
      path: /go
  commands:
  - go mod download

- name: test
  image: golang:1.21
  volumes:
    - name: deps
      path: /go
  commands:
  - make test

volumes:
- name: deps
  temp: {}
