AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  boston-archery-api


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Environment:
      Variables:
        ARCHERY_TABLE_NAME: ArcheryTag
        # need to specify these for local dev or they don't get picked up
        WEB_HOST:
        API_HOST:
        DISCORD_CLIENT_ID:
        DISCORD_CLIENT_SECRET:
        JWT_KEY:

Resources:
  SeasonsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: handlers.seasons.main
      Runtime: provided.al2
      Architectures:
        - arm64
      ReservedConcurrentExecutions: 5
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/v1/seasons
            Method: any
  AuthFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: handlers.auth.main
      Runtime: provided.al2
      Architectures:
        - arm64
      ReservedConcurrentExecutions: 5
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /auth/{proxy+}
            Method: any
