package tablekeys

const (
	PK = "PK"
	SK = "SK"

	GSI1_INDEX = "GSI1"
	GSI1PK     = "GSI1PK"
	GSI1SK     = "GSI1SK"

	SEASON_KEY_PREFIX     = "SEASON#"
	SEASON_GSI1_PK        = "SEASONS"
	SEASONNAME_KEY_PREFIX = "SEASONNAME#"

	PLAYER_KEY_PREFIX = "PLAYER#"
)
